// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCbLfjg4NGD0RvNl7yYAQbUjcgd9tVSNcQ',
//     appId: '1:283172018583:web:cbeba7c6dc2c62ae858cd2',
//     messagingSenderId: '283172018583',
//     projectId: 'contact-ae3a3',
//     authDomain: 'contact-ae3a3.firebaseapp.com',
//     storageBucket: 'contact-ae3a3.appspot.com',
//     measurementId: 'G-Y7KN5341HD',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDsNCKcyMHgsfbRSSlTgGYoNQq8zkpA3fs',
//     appId: '1:283172018583:android:35f067d37c87c88c858cd2',
//     messagingSenderId: '283172018583',
//     projectId: 'contact-ae3a3',
//     storageBucket: 'contact-ae3a3.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCd6yfxJAC2WFZI5X39Lq1Crx1GWpXg49g',
//     appId: '1:283172018583:ios:864f963bbb7bf661858cd2',
//     messagingSenderId: '283172018583',
//     projectId: 'contact-ae3a3',
//     storageBucket: 'contact-ae3a3.appspot.com',
//     iosBundleId: 'com.example.sdsApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyCd6yfxJAC2WFZI5X39Lq1Crx1GWpXg49g',
//     appId: '1:283172018583:ios:80af3fc582435edd858cd2',
//     messagingSenderId: '283172018583',
//     projectId: 'contact-ae3a3',
//     storageBucket: 'contact-ae3a3.appspot.com',
//     iosBundleId: 'com.example.sdsApp.RunnerTests',
//   );
// }
